stages:
  - build
  - deploy

run-amd64-build:
  stage: build
  image: faucet/dbuilder
  script:
    - apt-get update && apt-get upgrade -y
    - mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
    - export DEBEMAIL='maintainers@faucet.nz' && export DEBFULLNAME='Faucet Maintainers'
    - fakeroot debian/rules binary
    - mkdir built-packages/amd64/ || true
    - mv ../*.deb built-packages/amd64/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

run-armhf-build:
  stage: build
  image: faucet/dbuilder-pi
  script:
    - apt-get update && apt-get upgrade -y
    - mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
    - export DEBEMAIL='maintainers@faucet.nz' && export DEBFULLNAME='Faucet Maintainers'
    - fakeroot debian/rules binary
    - mkdir built-packages/armhf/ || true
    - mv ../*.deb built-packages/armhf/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

deploy-package:
  stage: deploy
  image: faucet/dbuilder
  script:
    - cd built-packages/
    - echo "{\"url\":\"https://packagecloud.io\",\"token\":\"$PACKAGECLOUD_TOKEN\"}" > ~/.packagecloud
    - package_cloud push faucetsdn/faucet/debian/jessie amd64/*.deb || true
    - package_cloud push faucetsdn/faucet/debian/stretch amd64/*.deb || true
    - package_cloud push faucetsdn/faucet/debian/buster amd64/*.deb || true
    - package_cloud push faucetsdn/faucet/raspbian/jessie armhf/*.deb || true
    - package_cloud push faucetsdn/faucet/raspbian/stretch armhf/*.deb || true
    - package_cloud push faucetsdn/faucet/raspbian/buster armhf/*.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/xenial amd64/*.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/yakkety amd64/*.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/zesty amd64/*.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/artful amd64/*.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/bionic amd64/*.deb || true
