stages:
  - build
  - deploy

build-amd64-debian-jessie:
  stage: build
  image: debian:jessie
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/debian_jessie/
    - mv ../*.deb built-packages/amd64/debian_jessie/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-amd64-debian-stretch:
  stage: build
  image: debian:stretch
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/debian_stretch/
    - mv ../*.deb built-packages/amd64/debian_stretch/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-amd64-debian-buster:
  stage: build
  image: debian:buster
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/debian_buster/
    - mv ../*.deb built-packages/amd64/debian_buster/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-armhf-debian-jessie:
  stage: build
  image: multiarch/debian-debootstrap:armhf-jessie
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/armhf/debian_jessie/
    - mv ../*.deb built-packages/armhf/debian_jessie/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-armhf-debian-stretch:
  stage: build
  image: multiarch/debian-debootstrap:armhf-stretch
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/armhf/debian_stretch/
    - mv ../*.deb built-packages/armhf/debian_stretch/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-armhf-debian-buster:
  stage: build
  image: multiarch/debian-debootstrap:armhf-buster
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/armhf/debian_buster/
    - mv ../*.deb built-packages/armhf/debian_buster/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-amd64-ubuntu-xenial:
  stage: build
  image: ubuntu:xenial
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/ubuntu_xenial/
    - mv ../*.deb built-packages/amd64/ubuntu_xenial/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-amd64-ubuntu-artful:
  stage: build
  image: ubuntu:artful
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/ubuntu_artful/
    - mv ../*.deb built-packages/amd64/ubuntu_artful/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

build-amd64-ubuntu-bionic:
  stage: build
  image: ubuntu:bionic
  script:
    - ./gitlab-build.sh
    - mkdir -p built-packages/amd64/ubuntu_bionic/
    - mv ../*.deb built-packages/amd64/ubuntu_bionic/
  artifacts:
    paths:
      - built-packages/*
    expire_in: 1 day

deploy-package:
  stage: deploy
  image: faucet/dbuilder
  script:
    - cd built-packages/
    - echo "{\"url\":\"https://packagecloud.io\",\"token\":\"$PACKAGECLOUD_TOKEN\"}" > ~/.packagecloud
    - package_cloud push faucetsdn/faucet/debian/jessie amd64/debian_jessie/*.deb || true
    - package_cloud push faucetsdn/faucet/debian/stretch amd64/debian_stretch/*.deb || true
    - package_cloud push faucetsdn/faucet/debian/buster amd64/debian_buster/*.deb || true
    - package_cloud push faucetsdn/faucet/raspbian/jessie armhf/debian_jessie/*.deb || true
    - package_cloud push faucetsdn/faucet/raspbian/stretch armhf/debian_stretch/*.deb || true
    - package_cloud push faucetsdn/faucet/raspbian/buster armhf/debian_buster/*.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/xenial amd64/ubuntu_xenial/*.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/artful amd64/ubuntu_artful/*.deb || true
    - package_cloud push faucetsdn/faucet/ubuntu/bionic amd64/ubuntu_bionic/*.deb || true
